#!/bin/bash
# sync-rules-to-agents.sh
# Auto-convert .claude/rules/*.md → codex/AGENTS.md + SSOT drift detection
#
# Usage:
#   ./scripts/codex/sync-rules-to-agents.sh           # Convert and write
#   ./scripts/codex/sync-rules-to-agents.sh --check   # Drift check only (no write)
#   ./scripts/codex/sync-rules-to-agents.sh --dry-run # Preview conversion output
#
# Output: Updates the ## Rules section in codex/AGENTS.md

set -euo pipefail

# ===== Configuration =====
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
RULES_DIR="${PROJECT_ROOT}/.claude/rules"
AGENTS_MD="${PROJECT_ROOT}/codex/AGENTS.md"
HASH_FILE="${PROJECT_ROOT}/.claude/state/rules-hash.txt"
SECTION_MARKER_START="<!-- sync-rules-to-agents: start -->"
SECTION_MARKER_END="<!-- sync-rules-to-agents: end -->"

# ===== Option parsing =====
MODE="write"
for arg in "$@"; do
  case "$arg" in
    --check)    MODE="check" ;;
    --dry-run)  MODE="dry-run" ;;
  esac
done

# ===== Get list of rule files =====
# Exclude CLAUDE.md as it is only for auto-generated memory context
RULE_FILES=()
while IFS= read -r f; do
  basename_f="$(basename "$f")"
  case "$basename_f" in
    CLAUDE.md) continue ;;  # Exclude memory context files
    *.md) RULE_FILES+=("$f") ;;
  esac
done < <(find "$RULES_DIR" -maxdepth 1 -name "*.md" | sort)

if [ ${#RULE_FILES[@]} -eq 0 ]; then
  echo "INFO: No rule files found in ${RULES_DIR}" >&2
  exit 0
fi

# ===== Convert rule content to AGENTS.md format =====
build_rules_section() {
  echo "${SECTION_MARKER_START}"
  echo ""
  echo "## Rules (from .claude/rules/)"
  echo ""
  echo "> This section is auto-generated by \`scripts/codex/sync-rules-to-agents.sh\`."
  echo "> Do not edit directly. The SSOT is \`.claude/rules/\`."
  echo ""
  echo "| Rule file | Description |"
  echo "|-----------|-------------|"

  for f in "${RULE_FILES[@]}"; do
    name="$(basename "$f" .md)"
    # Get description from frontmatter
    desc=$(awk '/^---/{count++; next} count==1 && /^description:/{sub(/^description:[[:space:]]*/, ""); print; exit}' "$f" 2>/dev/null || true)
    if [ -z "$desc" ]; then
      # If no frontmatter, use the first H1 heading
      desc=$(grep -m1 '^# ' "$f" 2>/dev/null | sed 's/^# //' || true)
    fi
    [ -z "$desc" ] && desc="${name}"
    echo "| \`${name}.md\` | ${desc} |"
  done

  echo ""

  # Expand important sections for each rule file
  for f in "${RULE_FILES[@]}"; do
    name="$(basename "$f" .md)"
    echo "### ${name}"
    echo ""
    # codex-cli-only.md: Rules for Claude Code (MCP deprecation/re-registration prohibition) are not needed in Codex environments
    # Codex itself does not need to call codex exec, so skip (reference link only)
    if [ "$name" = "codex-cli-only" ]; then
      echo "> This rule is for Claude Code. It does not apply in Codex environments."
    # test-quality.md: Expand the "Strictly Prohibited" section first (AGENTS.md format template)
    # Extract the prohibited pattern table and response flow and embed in AGENTS.md
    elif [ "$name" = "test-quality" ]; then
      awk '
        BEGIN { in_front=0; done_front=0; in_prohibited=0; lines=0 }
        /^---/ && !done_front { in_front=!in_front; if (!in_front) done_front=1; next }
        in_front { next }
        !done_front { next }
        /^## 絶対禁止事項/ { in_prohibited=1 }
        /^## / && !/^## 絶対禁止事項/ && in_prohibited { in_prohibited=0 }
        in_prohibited && lines < 40 { print; lines++ }
      ' "$f"
    # implementation-quality.md: Expand "Strictly Prohibited" and "Implementation Self-Check" sections
    # Embed hollow implementation prohibition pattern table + checklist into AGENTS.md
    elif [ "$name" = "implementation-quality" ]; then
      awk '
        BEGIN { in_front=0; done_front=0; in_section=0; lines=0 }
        /^---/ && !done_front { in_front=!in_front; if (!in_front) done_front=1; next }
        in_front { next }
        !done_front { next }
        /^## 絶対禁止事項|^## impl時のセルフチェック/ { in_section=1 }
        /^## / && !/^## 絶対禁止事項/ && !/^## impl時のセルフチェック/ && in_section { in_section=0 }
        in_section && lines < 60 { print; lines++ }
      ' "$f"
    else
      # Output the first 50 lines for other rule files
      awk '
        BEGIN { in_front=0; done_front=0; lines=0 }
        /^---/ && !done_front { in_front=!in_front; if (!in_front) done_front=1; next }
        in_front { next }
        done_front && lines < 50 { print; lines++ }
      ' "$f"
    fi
    echo ""
    echo "<!-- Full text: .claude/rules/${name}.md -->"
    echo ""
  done

  echo "${SECTION_MARKER_END}"
}

# ===== Compute hash of current rule content =====
compute_rules_hash() {
  cat "${RULE_FILES[@]}" | shasum -a 256 | awk '{print $1}'
}

CURRENT_HASH="$(compute_rules_hash)"

# ===== --check mode: drift detection only =====
if [ "$MODE" = "check" ]; then
  if [ ! -f "$HASH_FILE" ]; then
    echo "DRIFT: hash file not found (${HASH_FILE}). Run without --check to initialize." >&2
    exit 1
  fi
  SAVED_HASH="$(cat "$HASH_FILE" 2>/dev/null || true)"
  if [ "$CURRENT_HASH" = "$SAVED_HASH" ]; then
    echo "OK: rules are in sync (hash: ${CURRENT_HASH})"
    exit 0
  else
    echo "DRIFT: rules have changed since last sync." >&2
    echo "  saved:   ${SAVED_HASH}" >&2
    echo "  current: ${CURRENT_HASH}" >&2
    echo "  Run ./scripts/codex/sync-rules-to-agents.sh to update." >&2
    exit 1
  fi
fi

# ===== Write converted content to tmp file =====
NEW_SECTION_FILE="$(mktemp /tmp/harness-tmp.XXXXXX)"
build_rules_section > "$NEW_SECTION_FILE"

# ===== --dry-run mode: preview only =====
if [ "$MODE" = "dry-run" ]; then
  echo "=== DRY RUN: would write to ${AGENTS_MD} ==="
  echo ""
  cat "$NEW_SECTION_FILE"
  rm -f "$NEW_SECTION_FILE"
  exit 0
fi

# ===== write mode: update AGENTS.md =====
if [ ! -f "$AGENTS_MD" ]; then
  echo "ERROR: ${AGENTS_MD} not found." >&2
  rm -f "$NEW_SECTION_FILE"
  exit 1
fi

# If the existing section is present, replace it; otherwise append to the end
if grep -q "${SECTION_MARKER_START}" "$AGENTS_MD" 2>/dev/null; then
  # Replace existing section (swap content between markers using awk)
  TMP_FILE="$(mktemp /tmp/harness-tmp.XXXXXX)"
  awk -v new_file="$NEW_SECTION_FILE" \
    -v start="${SECTION_MARKER_START}" \
    -v end="${SECTION_MARKER_END}" '
    BEGIN { in_section=0; inserted=0 }
    $0 ~ start {
      in_section=1
      while ((getline line < new_file) > 0) { print line }
      close(new_file)
      inserted=1
      next
    }
    $0 ~ end   { in_section=0; next }
    !in_section { print }
  ' "$AGENTS_MD" > "$TMP_FILE"
  mv "$TMP_FILE" "$AGENTS_MD"
  echo "INFO: Updated existing Rules section in ${AGENTS_MD}"
else
  # If section does not exist, append to end
  printf '\n' >> "$AGENTS_MD"
  cat "$NEW_SECTION_FILE" >> "$AGENTS_MD"
  echo "INFO: Appended Rules section to ${AGENTS_MD}"
fi

rm -f "$NEW_SECTION_FILE"

# ===== Save hash =====
mkdir -p "$(dirname "$HASH_FILE")"
echo "$CURRENT_HASH" > "$HASH_FILE"
echo "INFO: Saved hash (${CURRENT_HASH}) to ${HASH_FILE}"

echo "DONE: sync complete."
